version: '3.4'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: "jenkins-docker"
    volumes:
        - $PWD/jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
    restart: always
    ports:
        - "8080:8080"
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

#docker exec jenkins-docker cat /var/jenkins_home/secrets/initialAdminPassword



